version: '3.8'

services:
  test-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - test_redis_data:/data
    restart: unless-stopped

  test-postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=test_finagent
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  test_redis_data:
  test_postgres_data: 