services:
  # Main FastAPI Application
  - type: web
    name: finagent-api
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: REDIS_URL
        fromService:
          type: redis
          name: finagent-redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: finagent-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  # Redis Cache
  - type: redis
    name: finagent-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  # PostgreSQL Database
  - name: finagent-db
    plan: starter
    databaseName: finagent
    user: finagent 