services:
  # Enhanced FinAgent API
  - type: web
    name: finagent-enhanced
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_enhanced_complete:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  # Redis Cache
  - type: redis
    name: finagent-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  # PostgreSQL Database
  - name: finagent-db
    plan: starter
    databaseName: finagent
    user: finagent 